[build]
  command = "npm install --include=dev && npm run build"
  publish = "client/dist"

[build.environment]
  VITE_API_URL = "https://hirko-gemechu-portfolio-website.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
